### ISSUE TITLE
barcode scanner without opening a new screen 

### ISSUE THREAD

**Issue by zahrabidi** [AseemWangoo/flutter_programs#1]
Hi
 I want to  load a barcode scanner in  a part of the screen  with specified height and width  without clicking a button and   opening a new screen 
but  the result that this code shows me  is not what I want (barcode scanner runs by clicking  on the button and opens a new screen )

please help me

**Comment by AseemWangoo** [comment]
Did you try using barcodeScanning function separately ? As in, instead of calling onPress, directly call the barcodeScanning ?

**Comment by zahrabidi** [comment]
![photo_2018-10-25_11-23-29](https://user-images.githubusercontent.com/43084690/47484664-2f258380-d849-11e8-9b56-d38d2c772d6b.jpg)
I want to use a barcode scanner like this  picture directly  without the onPress button or opening a new screen

**Comment by AseemWangoo** [comment]
Try calling the function on initState().

**Comment by zahrabidi** [comment]
Could you give me an example please I'm a beginner

**Comment by AseemWangoo** [comment]
@override
  void initState() {
    super.initState();
    barcodeScanning();
  }

**Comment by zahrabidi** [comment]
> @override
> void initState() {
> super.initState();
> barcodeScanning();
> }

Hi by this code first thing that   runs, is barcode scanning  
It isn't  thing that I want

**Comment by AseemWangoo** [comment]
For separate screen, i think it depends on the plugin owner...
May I know whether were you able to fix ?..
