### ISSUE TITLE
Hidden WebView not opening when called using flutterwebviewplugin.launch()

### ISSUE THREAD

**Issue by shubhammatta** [AseemWangoo/flutter_programs#2]
I was trying to run WebView.dart. I tried on both emulator and physical device.
'Open "hidden" Webview' is not working. 
After finishLoad state, the web View is not launched.
Any Suggestions regarding this?

**Comment by shubhammatta** [comment]
I think it might have to do with AppCacheSize and being out of memory. Is there any way to control the CacheSize of a webview?

**Comment by AseemWangoo** [comment]
I tried to increase the cache size once, still was failing.

May I suggest you to try the new Webview plugin by flutter team, [https://pub.dartlang.org/packages/webview_flutter]

Article : [https://medium.com/flutterpub/flutter-webview-and-sharing-apps-79615d7f9a0d]
