### ISSUE TITLE
where is file in  ‘’flutter_programs/GraphQL.dart“

### ISSUE THREAD

**Issue by njdmznkj** [AseemWangoo/flutter_programs#3]
I cannot find addStar.dart 、readRepositories.dart、feedList.dart ，Can you tell me where it is？

**Comment by AseemWangoo** [comment]
Kindly refer this [](https://github.com/zino-app/graphql-flutter/tree/master/example)

**Comment by AseemWangoo** [comment]
https://github.com/zino-app/graphql-flutter/tree/master/example
