### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by AkhilSajiCodzoc** [AseemWangoo/flutter_programs#8]
Can you do pagibation here?

**Comment by AseemWangoo** [comment]
I have implemented Pagination in Flutter Web

Source Code: https://github.com/AseemWangoo/experiments_with_web
Article: https://flatteredwithflutter.com/using-paginateddatatable-in-flutter-web/

For mobile, maybe you can look into this
https://gallery.flutter.dev/#/demo/data-table
